### ISSUE TITLE
Bug when starting a wizard in a room

### ISSUE THREAD

**Issue by cristianbica** [cristianbica/lita-wizard#3]
1. start a wizard in a room
2. the bot replies in the room with the initial message
3. the bot replies in the room with the first question
4. the bot expects my first answer in direct message

Ideally I would get in the room a message (I cannot run commands like this in a room so I'm gonna write you directly) and then get a direct message with the initial message and the first question.

**Comment by spkane** [comment]
see: https://github.com/cristianbica/lita-wizard/pull/4

**Comment by cristianbica** [comment]
Fixed by #4. Released as [v1.0.3](https://github.com/cristianbica/lita-wizard/releases/tag/v1.0.3)
